---
"$schema": http://json-schema.org/draft-04/hyper-schema
title: Service
description: API to return list of Service code and names, is defined to custom settings.
stability: prototype
strictProperties: true
type:
- object
definitions:
  code:
    description: unique identifier of Service
    example: 'cat'
    readOnly: true
    type:
    - string
  name:
    description: unique name of Service
    example: 'にゃんにゃん'
    readOnly: true
    type:
    - string
  start_date:
    description: date the service started
    example: '2010-03-01'
    type:
    - string
  end_date:
    description: date the service ended
    example: '2999-12-31'
    type:
    - string
  identity:
    anyOf:
    - "$ref": "/schemata/service#/definitions/code"
    - "$ref": "/schemata/service#/definitions/name"
links:
- description: List existing Service names.
  href: "/services"
  method: GET
  rel: instances
  title: List
properties:
  code:
    "$ref": "/schemata/service#/definitions/code"
  name:
    "$ref": "/schemata/service#/definitions/name"
  start_date:
    "$ref": "/schemata/service#/definitions/start_date"
  end_date:
    "$ref": "/schemata/service#/definitions/end_date"
id: schemata/service
